### ISSUE TITLE
AMV/Satwind Obs Validation

### ISSUE THREAD

**Issue by CoryMartin-NOAA** [NOAA-EMC/JEDI-T2O#40]
Need to validate satellite based winds/AMV observations from all platforms

This issue will track progress on validation of AMVs in UFO for GDAS in four stages:

- [x] HofX computation using GSI produced GeoVaLs
- [x] QC count checks (and YAML changes) using GSI produced GeoVaLs
- [x] Obs errors using GSI produced GeoVaLs
- [x] HofX computation in FV3-JEDI

Note this will need to include any near-surface correction applied to the observation/hofx value.

**Comment by BrettHoover-NOAA** [comment]
Running Cory's GDASApp (importing GSI grid into JEDI to remove interpolative differences in hofx) and EVA scripts on a yaml file designed for satwind QC, including all criteria in the ewok/jedi-gdas satwind yaml file located [here](https://github.com/NOAA-EMC/ufo/blob/develop/ewok/jedi-gdas/satwind.yaml). The test completes with some level of disagreement between JEDI and GSI on which observations are accepted and which are rejected. You can see these disagreements in the assignment of errors when GSI rejects an observation (assigns impossibly large errors) and JEDI doesn't:

![errordiff_vs_pressure_2021080100_satwind_northward_wind](https://user-images.githubusercontent.com/98188219/186275913-1176ea48-5052-488e-a07a-f990ad3a1b63.png)
This plot shows that there are disagreements throughout the troposphere on when errors should be assigned impossibly large (GSI rejected), including some other cases around 800 hPa where JEDI assigns an error much larger than GSI does.

Looking more closely at the u-component (eastward_wind), I found that when GSI passes (GSIeffectiveQC=0) and JEDI does not, JEDI's rejection flag is either 12 or 17. These correspond to either a Bounds Check (12) or a diffref (17) check, where MetaData is too far from reference. In my test data, I have the following breakdown of agreement or disagreement between JEDI and GSI's rejection criteria on satwinds:

![Screen Shot 2022-08-23 at 5 26 42 PM](https://user-images.githubusercontent.com/98188219/186277026-6bdf358b-5f54-4734-a682-9ae18feec128.png)

**Comment by BrettHoover-NOAA** [comment]
Focusing on the JEDI reject / GSI accept observations, nearly all of them (95%) are from a flag=12 (Bounds Check) failure in JEDI. I decided to try and crawl through these criteria to find the observations where disagreements are happening.

There are numerous Bounds Check filters in the yaml file, some of which are very difficult to simulate from the diag file. Of the ones I could easily simulate, I found that the most common disagreements that are being captured with my tests are coming from one particular filter:

![Screen Shot 2022-08-23 at 5 54 03 PM](https://user-images.githubusercontent.com/98188219/186279978-58ac6890-7e46-4b64-a78a-663ee0aa9a5c.png)

This is a check on  GOES IR (245), EUMET IR (253), and JMA IR (252)  satwinds to reject when pressure is outside of a 400 to 800 hPa range, based on the wording in the yaml filter:

```
# GOES IR (245), EUMET IR (253), JMA IR (252) reject when pressure between 400 and 800 mb.
  - filter: Bounds Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    test variables:
    - name: MetaData/air_pressure
    minvalue: 40000
    maxvalue: 80000
    where:
    - variable:
        name: ObsType/eastward_wind
      is_in: 245, 252, 253
    action:
      name: reject
```

However, the wording of the note on this filter points in the opposite direction, implying that the obs should be rejected if they are *within* the 400–800 hPa range. Checking this filter's settings against GSI code, I see no references to a 400 hPa cutoff but I do see references to an 800 hPa cutoff for Type 245 winds on Lines 1403-1404 of [read_satwnd.f90](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/read_satwnd.f90), but the cutoff goes in the opposite direction, rejecting observations at pressures above 800 hPa rather than below it:

```
              if( ppb >= 800.0_r_kind .and. ree >0.55_r_kind) then
                 qm=15
```
I'm wondering if this filter is set up incorrectly, or is the comment attached to it implying something it shouldn't? It seems like the maxvalue=80000 should correctly exclude Type=245 observations with pressures greater than 800 hPa, which matches what I see in the GSI. But the fact that so many of the rejection disagreements are showing up in this filter makes me think that something is possibly reversed here.

**Comment by CoryMartin-NOAA** [comment]
@BrettHoover-NOAA I think I agree with you (and it's worth at least trying), that YAML suggests that if it is between 400-800 hPa and is 245,252,253, to reject the obs. I think there are other 'actions' to try, but I don't know them off the top of my head. Perhaps 'accept' instead of 'reject'?

**Comment by BrettHoover-NOAA** [comment]
I found the range operation in GSI, in [setupw.f90 Lines 963–967](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/setupw.f90#L963-L967):
```
        if(itype ==245 ) then
           if( presw >399.0_r_kind .and. presw <801.0_r_kind) then  !GOES IR  winds
              error=zero                          !  no data between 400-800mb
           endif
        endif
```
So it looks like this filter is definitely operating in reverse, excluding what should be retained and retaining what should be excluded. Also, it looks like the filter operates a little differently for Type 252 winds, excluding between 500-800 hPa, while 400–800 is used again for Type 253 winds, [setupw.f90 Lines 968–975](https://github.com/NOAA-EMC/GSI/blob/develop/src/gsi/setupw.f90#L968-L975):
```
        if(itype == 252 .and. presw >499.0_r_kind .and. presw <801.0_r_kind) then  ! JMA IR winds
           error=zero
        endif
        if(itype == 253 )  then
           if(presw >401.0_r_kind .and. presw <801.0_r_kind) then  ! EUMET IR winds
              error=zero
           endif
        endif
```

**Comment by BrettHoover-NOAA** [comment]
I split this 400–800 pressure filter into 3 filters, applying the exact threshold values to each of the three observation types (245, 252, 253). At @CoryMartin-NOAA's suggestion I replaced the Bounds Check filter with the Perform Action filter, which will execute the reject action on any observation within the bounds, rather than those outside of it:

old filter:
```
  # GOES IR (245), EUMET IR (253), JMA IR (252) reject when pressure between 400 and 800 mb.
  - filter: Bounds Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    test variables:
    - name: MetaData/air_pressure
    minvalue: 40000
    maxvalue: 80000
    where:
    - variable:
        name: ObsType/eastward_wind
      is_in: 245, 252, 253
    action:
      name: reject
```

new filters:
```
  # GOES IR (245) reject when pressure between 399 and 801 mb.
  - filter: Perform Action
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    where:
    - variable: MetaData/air_pressure
      minvalue: 39900
      maxvalue: 80100
    where:
    - variable: ObsType/eastward_wind
      is_in: 245
    action:
      name: reject
  # JMA IR (252) reject when pressure between 499 and 801 mb.
  - filter: Perform Action
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    where:
    - variable: MetaData/air_pressure
      minvalue: 49900
      maxvalue: 80100
    where:
    - variable: ObsType/eastward_wind
      is_in: 252
    action:
      name: reject
  # EUMETSAT IR (253) reject when pressure between 401 and 801 mb.
  - filter: Perform Action
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    where:
    - variable: MetaData/air_pressure
      minvalue: 40100
      maxvalue: 80100
    where:
    - variable: ObsType/eastward_wind
      is_in: 253
    action:
      name: reject
```

It looks like this works, bringing GSI and JEDI into much greater agreement for these satwind types.

**Comment by BrettHoover-NOAA** [comment]
I am working on code to drill down into the different rejection criteria to find the source of the remaining disagreements. I have some python code that will draw in variables from the diag files and some very limited geovals data that I interpolate to the observations with `MetPy.interpolate.interpolate_to_points()`. I am trying to identify the observations that *should* be rejected by each filter, and then run those observations through a function to produce a contingency table of the GSI/JEDI QC outcomes:

Obs that pass both GSI and JEDI QC
Obs that fail GSI QC and pass JEDI QC
Obs that pass GSI QC and fail JEDI QC
Obs that fail both GSI and JEDI QC

A successful test should put all of the obs into only the top-most or bottom-most contingency field, and any observations that fall into the middle two categories are suspicious disagreements between GSI and JEDI. Results are very nearly (but not entirely) equal for both u-component and v-component winds, so I will focus on the u-component for now.

If we perform a contingency table check on all satwinds regardless of whether they fit into a rejection criteria or not, there is broad disagreement between GSI and JEDI, with only about 56% of satwinds in agreement and the remainder in disagreement:
```
all rejection criteria
    Total Obs: 1229931
     Flagged obs pass both GSI and JEDI QC 21.51% (264550)
     Flagged obs fail GSI and pass JEDI QC 23.42% (288013)
     Flagged obs pass GSI and fail JEDI QC 20.19% (248363)
     Flagged obs fail both GSI and JEDI QC 34.88% (429005)
```

If I focus on only those winds that should be caught by a JEDI filter, there is very broad agreement between GSI and JEDI QC. For example, all of the pressure-level filters are in perfect agreement, e.g.:
```
reject Type (245) inside of 399-801 hPa
    Total Obs: 45735
     Flagged obs pass both GSI and JEDI QC 0.00% (0)
     Flagged obs fail GSI and pass JEDI QC 0.00% (0)
     Flagged obs pass GSI and fail JEDI QC 0.00% (0)
     Flagged obs fail both GSI and JEDI QC 100.00% (45735)
```

The log-normal vector departure (LNVD) check on a subset of satwind types is also clean:
```
reject Type (244,247,257,258,259,260) LNVD>3.0
    Total Obs: 31214
     Flagged obs pass both GSI and JEDI QC 0.00% (0)
     Flagged obs fail GSI and pass JEDI QC 0.00% (0)
     Flagged obs pass GSI and fail JEDI QC 0.00% (0)
     Flagged obs fail both GSI and JEDI QC 100.00% (31214)
```

Some filters catch no observations at all and are effectively not applied, these include the gross checks of 130 m/s maximums for both components of the wind as well as the wind speed, and a check on a subset of satwind types constraining them to pressures less than 600 hPa.

There are two filters that show disagreements. First, the filter that rejects satwinds with more than a 50 degree difference with the model background, excluding observations with a u-component of less than 3.5 m/s:
```
reject direction diff > 50 & u>3.5
    Total Obs: 17276
     Flagged obs pass both GSI and JEDI QC 2.43% (419)
     Flagged obs fail GSI and pass JEDI QC 1.53% (264)
     Flagged obs pass GSI and fail JEDI QC 4.65% (803)
     Flagged obs fail both GSI and JEDI QC 91.40% (15790)
```

Second, the filter that rejects any satwind whose pressure level is within 100 hPa of the surface, based on interpolation of the `surface_pressure` geoval:
```
reject surface_pressure - ob_pressure < 100 hPa
    Total Obs: 122579
     Flagged obs pass both GSI and JEDI QC 0.00% (0)
     Flagged obs fail GSI and pass JEDI QC 0.00% (0)
     Flagged obs pass GSI and fail JEDI QC 38.22% (46850)
     Flagged obs fail both GSI and JEDI QC 61.78% (75729)
```

I am performing my own interpolation of the `surface_pressure` geoval to observation lat/lon using `MetPy.interpolate.interpolate_to_points()` here, since the interpolated value used in JEDI is not available in the diag file.

**Comment by BrettHoover-NOAA** [comment]
These two filters only account for 264 obs that fail GSI QC and pass JEDI QC, and 47,643 obs that pass GSI QC and fail JEDI QC. Based on the contingency table for all satwinds, this is only 0.092% and 19.2% of the total obs in these contingency categories, respectively.

There is another filter in the JEDI satwinds.yaml file that I have not checked, which rejects any observations 50 hPa above the (estimated) tropopause:
```
  # Multiple satellite platforms, reject when pressure is more than 50 mb above tropopause.
  - filter: Difference Check
    filter variables:
    - name: eastward_wind
    - name: northward_wind
    reference: TropopauseEstimate@ObsFunction
    value: MetaData/air_pressure
    minvalue: -5000                    # 50 hPa above tropopause level, negative p-diff
    action:
      name: reject
```
This is described as applying to "multiple satellite platforms", though there is no satwind Type constraint being applied here, so it is being applied to all satwinds. The `TropopauseEstimate` function is a crude function but I don't have the details to replicate it in my code, so I can't directly test this filter. However, looking at the pressure distribution of the observations that either pass GSI and fail JEDI, or fail GSI and pass JEDI, there appears to be some pressure dependence:
![contingency_table_fig01](https://user-images.githubusercontent.com/98188219/187747973-dab74aa0-4a88-4f78-a6b1-cada96c99e12.png)
There is an almost perfectly sharp cutoff in GSI-pass/JEDI-fail satwinds that keeps them at pressures either greater than 800 hPa or less than 400 hPa. And there is a large proportion of total satwinds at pressures less than 200 hPa that fall into GSI-fail/JEDI-pass.
