### ISSUE TITLE
Apply bias correction to aircraft temperature measurements

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/JEDI-T2O#65]
The temperature bias correction for aircraft measurements is currently missing from UFO.

There is a [UFO Issue](https://github.com/JCSDA-internal/ufo/issues/2149) to address this, but this issue has been created to focus on the reduced problem of how to read in a CSV file with the coefficients and to apply this bias correction to the H(x) (i.e., ignoring for now the larger problem of how to update the coefficients within the minimization).

This issue references [JEDI-T2O Issue 60](https://github.com/NOAA-EMC/JEDI-T2O/issues/60).

**Comment by ADCollard** [comment]
Confirming that the bias correction in UFO is applied to H(x) and not to the observations:

[ObsOperator.cc](https://github.com/JCSDA-internal/ufo/blob/develop/src/ufo/ObsOperator.cc)
```
// -----------------------------------------------------------------------------

void ObsOperator::simulateObs(const GeoVaLs & gvals, ioda::ObsVector & yy,
                              const ObsBias & biascoeff, ioda::ObsVector & ybias,
                              ObsDiagnostics & ydiags) const {
  oper_->simulateObs(gvals, yy, ydiags);
  if (biascoeff) {
    ObsBiasOperator biasoper(odb_);
    biasoper.computeObsBias(gvals, ybias, biascoeff, ydiags);
    // update H(x) with bias correction
    yy += ybias;
  }
}
```

**Comment by BrettHoover-NOAA** [comment]
First crack at trying to untangle this problem, let me know if anything seems wrong about this approach, the UFO code is pretty opaque so a lot of this is conjecture on my part.

Calling back to https://github.com/JCSDA-internal/ufo/issues/2149, the full suite of predictors broken out by tail numbers would look something like this in a set of 3 csv files (this is assuming `MetaData/sequenceNumber` is the aircraft tail-number):

constant coefficient values:
```
MetaData/sequenceNumber,BiasCoefficientValue/constantPredictor
int,float
00000000,0.000021
00000674,0.150858
00000727,-0.252591
00000737,0.024460
00000752,-0.438555
00000758,-1.230313
00000765,-0.000105
00000771,0.423237
00000772,0.744413
00000775,-3.377616
...
```
ascent-rate coefficient values:
```
MetaData/sequenceNumber,BiasCoefficientValue/ascentPredictor
int,float
00000000,0.000011
00000674,-0.000154
00000727,0.021926
00000737,0.014595
00000752,-0.013559
00000758,0.006147
00000765,-0.000042
00000771,0.018915
00000772,0.014224
000007756,0.128808
...
```
squared ascent-rate coefficient values:
```
MetaData/sequenceNumber,BiasCoefficientValue/ascentSquaredPredictor
int,float
00000000,0.000697
00000674,-0.000011
00000727,-0.000494
00000737,0.000408
00000752,-0.000297
00000758,0.001780
00000765,-0.000235
00000771,-0.000030
00000772,0.006476 
00000775,-0.080778
...
```
From the documentation on `DrawValueFromFile` [here](https://jointcenterforsatellitedataassimilation-jedi-docs.readthedocs-hosted.com/en/latest/inside/jedi-components/ufo/qcfilters/obsfunctions/DrawValueFromFile.html#drawvaluefromfile), these values can be drawn each in-turn from YAML using the following template:
```
- filter: Variable Assignment
  assignments:
  - name: <some-new-variable-name>
    function:
      name: ObsFunction/DrawValueFromFile
      options:
        file: <path-to-input>    # path to the CSV/NetCDF file
        group: BiasCoefficientValue
        interpolation:
        - name: MetaData/sequenceNumber
          method: exact
```

Note: Documentation for `DrawFromFile` specifies that there is only one column that can contain retrievable data, while the remaining columns have to be coordinate values used to identify the retrievable value. So I don't believe we can pack all of these into one csv file, although I don't think it would be hard to start with a single csv file containing the tail-numbers and all predictors as separate columns and then split the csv into its component parts prior to running the code.

We could use the `DrawFromFile` functionality to extract the predictor values from csv for each tail-number in the IODA aircraft data and assign them to variable-names (maybe `constantPredictor`, `ascentPredictor`, and `ascentSquaredPredictor`? the documentation isn't clear on if there needs to be a group-name but if so maybe we can use `BiasCoefficientValue/`).

Would it be a short lift from this point to performing the bias correction? Can we make three functions in https://github.com/JCSDA-internal/ufo/tree/develop/src/ufo/predictors similar to the satellite-based predictor functions that are already present (or 2 functions and reuse `Constant` for our constant coefficient) to construct the bias correction? It seems like `PredictorBase` is generalized enough that we might be able to use these tools to construct our own predictor-generator code?

**Comment by ADCollard** [comment]
@BrettHoover-NOAA This seems like a reasonable approach to me.

**Comment by BrettHoover-NOAA** [comment]
Slightly more refined version of this methodology, leaving the door open in step-2 for either applying `Predictor` functions or generating our own code, or something in-between:

Aircraft Bias Correction:

1. Generate predictor coefficients using `ObsFunction/DrawValueFromFile`, store in `BiasCoefficientValue/<predictor-name>` via `Variable Assignment`
```
- filter: Variable Assignment
  assignments:
  - name: BiasCoefficientValue/constantPredictor
    function:
      name: ObsFunction/DrawValueFromFile
      options:
        file: /path/to/aircraft/constant/bias_correction.csv    # path to the CSV file
        group: BiasCoefficientValue
        interpolation:
        - name: MetaData/sequenceNumber
          method: exact

- filter: Variable Assignment
  assignments:
  - name: BiasCoefficientValue/ascentPredictor
    function:
      name: ObsFunction/DrawValueFromFile
      options:
        file: /path/to/aircraft/ascent/bias_correction.csv    # path to the CSV file
        group: BiasCoefficientValue
        interpolation:
        - name: MetaData/sequenceNumber
          method: exact

- filter: Variable Assignment
  assignments:
  - name: BiasCoefficientValue/ascentSquaredPredictor
    function:
      name: ObsFunction/DrawValueFromFile
      options:
        file: /path/to/aircraft/ascentSquared/bias_correction.csv    # path to the CSV file
        group: BiasCoefficientValue
        interpolation:
        - name: MetaData/sequenceNumber
          method: exact
```
2. Generate predictors using ???, store in `BiasCorrectionPredictor/<predictor-name>` using `Variable Assignment`

NOTE: This function should take the `BiasCoefficientValue/<predictor-name>` and multiply it by the `<predictor-name>` to generate `BiasCorrectionPredictor/<predictor-name>`, i.e.:
```
BiasCorrectionPredictor/constantPredictor = ones(nobs) * BiasCoefficientValue/constantPredictor
BiasCorrectionPredictor/ascentPredictor = <ascent> * BiasCoeffcientValue/ascentPredictor
BiasCorrectionPredictor/ascentSquaredPredictor = <ascentSquared> * BiasCoefficientValue/ascentSquaredPredictor
```
```
- filter: Variable Assignment
  assignments:
  - name: BiasCorrectionPredictor/constantPredictor
    function:
      name: ???
      …

- filter: Variable Assignment
  assignments:
  - name: BiasCorrectionPredictor/ascentPredictor
    function:
      name: ???
      …

- filter: Variable Assignment
  assignments:
  - name: BiasCorrectionPredictor/ascentSquaredPredictor
    function:
      name: ???
      …
```

3. Compute a bias-corrected `airTemperature` using `ObsFunction/LinearCombination`, store in `DerivedObsValue/airTemperature` via `Variable Assignment`

```
- filter: Variable Assignment
  assignments:
  - name: DerivedObsValue/airTemperature
    type: float
    function:
      name: ObsFunction/LinearCombination
      options:
        variables: [ObsValue/airTemperature, BiasCorrectionPredictor/constantPredictor, BiasCorrectionPredictor/ascentPredictor, BiasCorrection/ascentSquaredPredictor]
        coefs: [1.0, 1.0, 1.0, 1.0]
```
