### ISSUE TITLE
Aircraft UFO evaluation

### ISSUE THREAD

**Issue by ADCollard** [NOAA-EMC/JEDI-T2O#92]
This issue is splitting from https://github.com/NOAA-EMC/JEDI-T2O/issues/60 so the sonde and aircraft validation does not get confused.

The starting point for this is the [GMAO YAML](https://github.com/GEOS-ESM/swell/tree/develop/src/swell/configuration/jedi/interfaces/geos_atmosphere/observations/aircraft.yaml), but there are many issues with these it appears.

The test YAMLs used here are in [this branch](https://github.com/NOAA-EMC/GDASApp/tree/feature/gmao_eval/parm/atm/obs/testing/swell).

**Comment by ADCollard** [comment]
Initial validation does not look good.  HofX is OK except for temperature where the bias correction is not being applied properly it seems.  But the observation errors are a complete mess.

![hofxdiff_vs_pressure_diag_aircraft_2021080100_Aircraft_airTemperature](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/82269f6c-bc67-449e-81fc-37df8c3e0033)
![hofxdiff_vs_pressure_diag_aircraft_2021080100_Aircraft_specificHumidity](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/09f0faf0-d498-4335-9799-97089f693d17)
![hofxdiff_vs_pressure_diag_aircraft_2021080100_Aircraft_windEastward](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/086f7eaf-e25f-4f46-8a86-8ef2532edabb)
![hofxdiff_vs_pressure_diag_aircraft_2021080100_Aircraft_windNorthward](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/5797ac77-f1c0-465b-a1d9-2051fae523b1)
![errordiff_vs_pressure_diag_aircraft_2021080100_Aircraft_airTemperature](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/84b447bf-8121-4186-9cca-39c1164e2c30)
![errordiff_vs_pressure_diag_aircraft_2021080100_Aircraft_specificHumidity](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/d5b762aa-16f1-4863-b3d9-7700f1b98449)
![errordiff_vs_pressure_diag_aircraft_2021080100_Aircraft_windEastward](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/f0a0e2e0-0f15-44c7-a8c6-e33fabbb5f32)
![errordiff_vs_pressure_diag_aircraft_2021080100_Aircraft_windNorthward](https://github.com/NOAA-EMC/JEDI-T2O/assets/40322596/79f938a1-a0e6-4968-a107-6d99a0bf9b6d)

**Comment by BrettHoover-NOAA** [comment]
The issue with reassigning the value of `hofx/airTemperature` to a bias-corrected value is extremely picky. If I do the `Variable Assignment` to a new variable `HofXBC/airTemperature`, the value of `hofx/airTemperature` remains not-bias-corrected but the new variable is bias-corrected. If I try to bias-correct `hofx/airTemperature` directly and write the result of the `LinearCombination` function to the variable, no result (remains not-bias-corrected). If I do the bias-correction to `HofXBC/airTemperature` and then reassign `hofx/airTemperature` to the bias-corrected values using another `Variable Asssignment` filter:

```
# Use ObsFunction/LinearCombination to combine ObsValue/airTemperature with the
# BiasCorrectionPredictor/<predictor> variables to produce a bias-corrected
# HofX
- filter: Variable Assignment
  assignments:
  - name: HofXBC/airTemperature
    type: float
    function:
      name: ObsFunction/LinearCombination
      options:
        variables: [HofX/airTemperature, BiasCorrectionTerm/constantPredictor, BiasCorrectionTerm/ascentPredictor, BiasCorrectionTerm/ascentSquaredPredictor]
        coefs: [1.0, 1.0, 1.0, 1.0]

- filter: Variable Assignment
  assignments:
  - name: hofx/airTemperature
    type: float
    source variable: HofXBC/airTemperature
```

The diag-file produces a bias-corrected `HofXBC/airTemperature` but `hofx/airTemperature` remains not-bias-corrected.

**Comment by BrettHoover-NOAA** [comment]
I was able to get UFO aircraft `airTemperature` acceptance to match GSI using the following method:

1. The `ObsError/airTemperature` value is first directly borrowed from GSI using `ObsFunction/LinearOperator` in a `Variable Assignment` filter:
```
# Make a copy of GsiAdjustObsError called GsiAdjustObsError2, for storing inflated error from ObsErrorFactorPressureCheck
- filter: Variable Assignment
  assignments:
  - name: GsiAdjustObsError2/airTemperature
    type: float  # type must be specified if the variable doesn't already exist
    source variable: GsiAdjustObsError/airTemperature
# Reassign obs error to copy of GsiAdjustObsError
- filter: Perform Action
  filter variables:
  - name: airTemperature
  action:
    name: assign error
    error function: 
      name: ObsFunction/LinearCombination
      options:
        variables: [GsiAdjustObsError2/airTemperature]
        coefs: [1.0]
```
There are two steps in the YAML here, one to assign a new variable `GsiAdjustObsError2/airTemperature` and then use it to assign `ObsError/airTemperature`. Ultimately this is probably not explicitly necessary and we could probably assign `GsiAdjustObsError/airTemperature` directly, but for full disclosure this is the current version of my YAML code.

It is also worth recognizing that this is a shortcut that will have to eventually be replaced with YAML filters that can properly assign the "adjust" error values without relying on GSI data.

2. The `ObsError/airTemperature` is inflated based on multiple criteria: `ObsFunction/ObsErrorFactorPressureCheck` is used to inflate errors based on the observation being close to the top or bottom level of the model, and an error inflation of factor `1.2` is applied for any observation with all zero-values for bias-correction coefficients (in offline bias correction, this will apply equally to observations with all zero-values in the corresponding GSI bias correction coefficient file, and observations that do not appear in the GSI bias correction coefficient file that are automatically assigned zero values for all coefficients by `ObsFunction/DrawValueFromFile`):
```
# Inflate ob-error based on pressure check (penalize observations too close to model top or bottom)
- filter: Perform Action
  filter variables:
  - name: airTemperature
  action:
    name: inflate error
    inflation variable:
      name: ObsFunction/ObsErrorFactorPressureCheck
      options:
        variable: airTemperature
        inflation factor: 8.0  # 4.0 for wind observations, 8.0 for temperature/humidity observations
        geovar_sfc_geomz: surface_altitude 
        test_qcflag: PreUseFlag

# inflate error for tails with uninitialized bias coefficients (i.e. all coefficients equal to zero)
# NOTE: Since the ObsFunction/DrawValueFromFile system used in offline bias correction assigns a zero
#       to all predictor coefficients for a tail-number not in the coefficients file, this filter will
#       correctly apply a 1.2 factor to the observation error for both unknown tail-numbers as well as
#       tail-numbers that are "new" (registered in coefficients file but have yet to be assigned
#       coefficients other than the initial zero-values)
- filter: Perform Action
  action:
    name: inflate error
    inflation factor: 1.2
  filter variables:
  - name: airTemperature
  where:
  - variable:
      name: BiasCorrectionTerm/constantPredictor
    is_close_to_any_of: [0.0]
    absolute_tolerance: 1.0e-6
  - variable:
      name: BiasCoefficientValue/ascentPredictor
    is_close_to_any_of: [0.0]
    absolute_tolerance: 1.0e-6
  - variable:
      name: BiasCoefficientValue/ascentSquaredPredictor
    is_close_to_any_of: [0.0]
    absolute_tolerance: 1.0e-6
```
An additional error inflation filter, `ObsFunction/ObsErrorFactorConventional` is used to inflate errors based on the density of observations in a model level, but this is presumed to already be present in the GSI "adjust" errors.

3. Guard-rails are applied to `ObsError/airTemperature` to conform to the provided minimum and maximum allowable values for the gross-error check, and the gross-error check coefficient is applied, using `ObsFunction/ObsErrorBoundConventional`. These values are saved to a new variable `ObsErrorBound/airTemperature` using the `Variable Assignment` filter. These values are then adjusted for any observation with a `PreQC/airTemperature` value of `3` to use a penalized gross-error check coefficient that is multiplied by `0.7`:
```
# Apply guard-rails to airTemperature ObsErrors and write to a separate variable
- filter: Variable Assignment
  assignments:
  - name: ObsErrorBound/airTemperature
    type: float
    function:
      name: ObsFunction/ObsErrorBoundConventional
      options:
        obsvar: airTemperature
        obserr_bound_min: 1.3
        obserr_bound_max: 5.6
        obserr_bound_factor: 7.0  # cgross
# Penalize obserr_bound_factor by factor of 0.7 if PreQC/airTemperature is 3
- filter: Variable Assignment
  where:
  - variable: PreQC/airTemperature
    is_in: [3]
  assignments:
  - name: ObsErrorBound/airTemperature
    type: float
    function:
      name: ObsFunction/ObsErrorBoundConventional
      options:
        obsvar: airTemperature
        obserr_bound_min: 1.3
        obserr_bound_max: 5.6
        obserr_bound_factor: 4.9  # cgross
```
4. The gross-error check is performed using the `Bounds Check` filter and using `ObsErrorBound/airTemperature` for an `absolute threshold` value, and `HofXBc` is passed as `test_hofx` to utilize the offline bias corrected values of HofX in the comparison:
```
# Gross check as a Background Check, utilizing threshold applied to ObsErrorBound/airTemperature
- filter: Background Check
  filter variables:
  - name: airTemperature
  function absolute threshold:
  - name: ObsErrorBound/airTemperature
  test_hofx: HofXBc
  action:
    name: reject
```
A 100% acceptance between UFO and GSI is reached.
